-- CreateEnum

CREATE TABLE IF NOT EXISTS "users" (
  "id" VARCHAR(255) PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "daily_logs" (
  "id" VARCHAR(255) PRIMARY KEY,
  "userId" VARCHAR(255) NOT NULL REFERENCES "users"("id"),
  "date" DATE NOT NULL,
  "sleep" INTEGER NOT NULL DEFAULT 1,
  "nutrition" INTEGER NOT NULL DEFAULT 1,
  "caffeine" INTEGER NOT NULL DEFAULT 1,
  "alcohol" INTEGER NOT NULL DEFAULT 1,
  "activity" INTEGER NOT NULL DEFAULT 1,
  "mood" INTEGER NOT NULL DEFAULT 1,
  "wellbeing" INTEGER NOT NULL DEFAULT 1,
  "stress" INTEGER NOT NULL DEFAULT 1,
  "energy" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE("userId", "date")
);

-- Table: users
CREATE TABLE IF NOT EXISTS "users" (
  "id" VARCHAR(255) PRIMARY KEY,
  "email" VARCHAR(255) UNIQUE NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Table: daily_logs
CREATE TABLE IF NOT EXISTS "daily_logs" (
  "id" VARCHAR(255) PRIMARY KEY,
  "userId" VARCHAR(255) NOT NULL REFERENCES "users"("id"),
  "date" DATE NOT NULL,
  "sleep" INTEGER NOT NULL DEFAULT 1,
  "nutrition" INTEGER NOT NULL DEFAULT 1,
  "caffeine" INTEGER NOT NULL DEFAULT 1,
  "alcohol" INTEGER NOT NULL DEFAULT 1,
  "activity" INTEGER NOT NULL DEFAULT 1,
  "mood" INTEGER NOT NULL DEFAULT 1,
  "wellbeing" INTEGER NOT NULL DEFAULT 1,
  "stress" INTEGER NOT NULL DEFAULT 1,
  "energy" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE("userId", "date")
);